### ISSUE TITLE
Allow for all printable characters in gen_random()

### ISSUE THREAD

**Issue by dallbee** [Sadin/osc0#1]
Why restrict it to just the alphabet?

**Comment by Sadin** [comment]
Attempted this in commit: 0408570

However not closing because upon running some of the printed values dont appear to be length specified of 8.

**Comment by Sadin** [comment]
Also @dallbee I have not looked at the pull request yet. Waiting on you to give me the okay tomorrow.

**Comment by dallbee** [comment]
That's a side effect of UTF-8. They are in fact all of length 8, they just don't display that way.

Good work.
